create table public.pronunciations (
    id bigint generated by default as identity primary key,
    word text not null,
    pronunciation text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    is_active boolean default true not null
);

-- Create a unique index on word for active pronunciations
create unique index pronunciations_word_active_idx on public.pronunciations (word) where (is_active = true);

-- Set up Row Level Security (RLS)
alter table public.pronunciations enable row level security;

-- Create policies
create policy "Enable read access for all users" on public.pronunciations
    for select
    using (true);

create policy "Enable insert for authenticated users only" on public.pronunciations
    for insert
    with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.pronunciations
    for update
    using (auth.role() = 'authenticated')
    with check (auth.role() = 'authenticated');

-- Grant access to authenticated users
grant all on public.pronunciations to authenticated; 