// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaqfxjmvtdhrfbmdhais.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhcWZ4am12dGRocmZibWRoYWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzYzMzUsImV4cCI6MjA2MzU1MjMzNX0.UiNRXhSBTgLdRfStJrv-ontarKh7Hrfv_olrpC9waXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);